"""
Django settings for projeto project.

pre requisito : pip install django-pyodbc-azure
validar: driver_sqlserver

Generated by 'django-admin startproject' using Django 2.1.1.



For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from __key__ import key, ip

driver_sqlserver = 'ODBC Driver 17 for SQL Server'


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


SECRET_KEY = '#_ldt5y=6pq&h3oxb)d7dfdz+rtjtpmkf2fa1=y^1s*k!)ho&h'

DEBUG = True

ALLOWED_HOSTS = ['10.10.4.82', 'localhost', '127.0.0.1']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'rest_framework',
    'bootstrapform',
    

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projeto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [''],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projeto.wsgi.application'


DATABASES = {
    'default': {
        'NAME': 'DJANGO',
        'ENGINE': 'sql_server.pyodbc',
        'HOST': ip['sqlserver_planejamento'],
        'USER': 'usr_mis',
        'PASSWORD': key['pw_usr_mis'],
        'OPTIONS': {
            'driver': driver_sqlserver,
        },
    },

    'mssql': {
        'NAME': 'CODIGOS',
        'ENGINE': 'sql_server.pyodbc',
        'HOST': ip['sqlserver_planejamento'],
        'USER': 'planejamento',
        'PASSWORD': key['pw_planejamento'],
        'OPTIONS': {
            'driver': driver_sqlserver,
        },
    },

}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'pt-BR'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = False


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
DATABASE_ROUTERS = ['app.db_router.DatabaseRouter']

MEDIA_URL = '/media/'
MEDIA_ROOT = 'media'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/home/'
